# Generated by Django 5.1.6 on 2025-02-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_file', models.FileField(upload_to='voices/')),
                ('predicted_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('user_feedback', models.BooleanField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
